// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/room/room.proto

package roompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildingId    string                 `protobuf:"bytes,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	BuildingName  string                 `protobuf:"bytes,3,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,4,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RoomType      string                 `protobuf:"bytes,6,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Equipment     []string               `protobuf:"bytes,8,rep,name=equipment,proto3" json:"equipment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_room_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

func (x *Room) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *Room) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *Room) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Room) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *Room) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Room) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *Room) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildingId    string                 `protobuf:"bytes,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	BuildingName  string                 `protobuf:"bytes,2,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,3,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RoomType      string                 `protobuf:"bytes,5,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Equipment     []string               `protobuf:"bytes,7,rep,name=equipment,proto3" json:"equipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_room_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomRequest) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

func (x *CreateRoomRequest) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *CreateRoomRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *CreateRoomRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateRoomRequest) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *CreateRoomRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRoomRequest) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	BuildingId    string                 `protobuf:"bytes,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	BuildingName  string                 `protobuf:"bytes,3,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,4,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RoomType      string                 `protobuf:"bytes,6,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Equipment     []string               `protobuf:"bytes,8,rep,name=equipment,proto3" json:"equipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_proto_room_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateRoomRequest) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

func (x *UpdateRoomRequest) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *UpdateRoomRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *UpdateRoomRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UpdateRoomRequest) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *UpdateRoomRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRoomRequest) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type GetRoomByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomByIdRequest) Reset() {
	*x = GetRoomByIdRequest{}
	mi := &file_proto_room_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomByIdRequest) ProtoMessage() {}

func (x *GetRoomByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRoomByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomByIdRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_proto_room_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{4}
}

type SearchAvailableRoomsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartTime         string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MinCapacity       int32                  `protobuf:"varint,3,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	RequiredEquipment []string               `protobuf:"bytes,4,rep,name=required_equipment,json=requiredEquipment,proto3" json:"required_equipment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchAvailableRoomsRequest) Reset() {
	*x = SearchAvailableRoomsRequest{}
	mi := &file_proto_room_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAvailableRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAvailableRoomsRequest) ProtoMessage() {}

func (x *SearchAvailableRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAvailableRoomsRequest.ProtoReflect.Descriptor instead.
func (*SearchAvailableRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{5}
}

func (x *SearchAvailableRoomsRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SearchAvailableRoomsRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *SearchAvailableRoomsRequest) GetMinCapacity() int32 {
	if x != nil {
		return x.MinCapacity
	}
	return 0
}

func (x *SearchAvailableRoomsRequest) GetRequiredEquipment() []string {
	if x != nil {
		return x.RequiredEquipment
	}
	return nil
}

type RoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	mi := &file_proto_room_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{6}
}

func (x *RoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_proto_room_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{7}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListRoomsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_room_room_proto protoreflect.FileDescriptor

const file_proto_room_room_proto_rawDesc = "" +
	"\n" +
	"\x15proto/room/room.proto\x12\x04room\"\x8b\x02\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\tR\n" +
	"buildingId\x12#\n" +
	"\rbuilding_name\x18\x03 \x01(\tR\fbuildingName\x12\x1f\n" +
	"\vroom_number\x18\x04 \x01(\tR\n" +
	"roomNumber\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12\x1b\n" +
	"\troom_type\x18\x06 \x01(\tR\broomType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1c\n" +
	"\tequipment\x18\b \x03(\tR\tequipment\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\xe9\x01\n" +
	"\x11CreateRoomRequest\x12\x1f\n" +
	"\vbuilding_id\x18\x01 \x01(\tR\n" +
	"buildingId\x12#\n" +
	"\rbuilding_name\x18\x02 \x01(\tR\fbuildingName\x12\x1f\n" +
	"\vroom_number\x18\x03 \x01(\tR\n" +
	"roomNumber\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12\x1b\n" +
	"\troom_type\x18\x05 \x01(\tR\broomType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tequipment\x18\a \x03(\tR\tequipment\"\x82\x02\n" +
	"\x11UpdateRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\tR\n" +
	"buildingId\x12#\n" +
	"\rbuilding_name\x18\x03 \x01(\tR\fbuildingName\x12\x1f\n" +
	"\vroom_number\x18\x04 \x01(\tR\n" +
	"roomNumber\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12\x1b\n" +
	"\troom_type\x18\x06 \x01(\tR\broomType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1c\n" +
	"\tequipment\x18\b \x03(\tR\tequipment\"-\n" +
	"\x12GetRoomByIdRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x12\n" +
	"\x10ListRoomsRequest\"\xa9\x01\n" +
	"\x1bSearchAvailableRoomsRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12!\n" +
	"\fmin_capacity\x18\x03 \x01(\x05R\vminCapacity\x12-\n" +
	"\x12required_equipment\x18\x04 \x03(\tR\x11requiredEquipment\"H\n" +
	"\fRoomResponse\x12\x1e\n" +
	"\x04room\x18\x01 \x01(\v2\n" +
	".room.RoomR\x04room\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x11ListRoomsResponse\x12 \n" +
	"\x05rooms\x18\x01 \x03(\v2\n" +
	".room.RoomR\x05rooms\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd2\x02\n" +
	"\vRoomService\x129\n" +
	"\n" +
	"CreateRoom\x12\x17.room.CreateRoomRequest\x1a\x12.room.RoomResponse\x129\n" +
	"\n" +
	"UpdateRoom\x12\x17.room.UpdateRoomRequest\x1a\x12.room.RoomResponse\x12;\n" +
	"\vGetRoomById\x12\x18.room.GetRoomByIdRequest\x1a\x12.room.RoomResponse\x12<\n" +
	"\tListRooms\x12\x16.room.ListRoomsRequest\x1a\x17.room.ListRoomsResponse\x12R\n" +
	"\x14SearchAvailableRooms\x12!.room.SearchAvailableRoomsRequest\x1a\x17.room.ListRoomsResponseB?Z=github.com/Aruzhan38/smart-campus-generated/proto/room;roompbb\x06proto3"

var (
	file_proto_room_room_proto_rawDescOnce sync.Once
	file_proto_room_room_proto_rawDescData []byte
)

func file_proto_room_room_proto_rawDescGZIP() []byte {
	file_proto_room_room_proto_rawDescOnce.Do(func() {
		file_proto_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_room_proto_rawDesc), len(file_proto_room_room_proto_rawDesc)))
	})
	return file_proto_room_room_proto_rawDescData
}

var file_proto_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_room_room_proto_goTypes = []any{
	(*Room)(nil),                        // 0: room.Room
	(*CreateRoomRequest)(nil),           // 1: room.CreateRoomRequest
	(*UpdateRoomRequest)(nil),           // 2: room.UpdateRoomRequest
	(*GetRoomByIdRequest)(nil),          // 3: room.GetRoomByIdRequest
	(*ListRoomsRequest)(nil),            // 4: room.ListRoomsRequest
	(*SearchAvailableRoomsRequest)(nil), // 5: room.SearchAvailableRoomsRequest
	(*RoomResponse)(nil),                // 6: room.RoomResponse
	(*ListRoomsResponse)(nil),           // 7: room.ListRoomsResponse
}
var file_proto_room_room_proto_depIdxs = []int32{
	0, // 0: room.RoomResponse.room:type_name -> room.Room
	0, // 1: room.ListRoomsResponse.rooms:type_name -> room.Room
	1, // 2: room.RoomService.CreateRoom:input_type -> room.CreateRoomRequest
	2, // 3: room.RoomService.UpdateRoom:input_type -> room.UpdateRoomRequest
	3, // 4: room.RoomService.GetRoomById:input_type -> room.GetRoomByIdRequest
	4, // 5: room.RoomService.ListRooms:input_type -> room.ListRoomsRequest
	5, // 6: room.RoomService.SearchAvailableRooms:input_type -> room.SearchAvailableRoomsRequest
	6, // 7: room.RoomService.CreateRoom:output_type -> room.RoomResponse
	6, // 8: room.RoomService.UpdateRoom:output_type -> room.RoomResponse
	6, // 9: room.RoomService.GetRoomById:output_type -> room.RoomResponse
	7, // 10: room.RoomService.ListRooms:output_type -> room.ListRoomsResponse
	7, // 11: room.RoomService.SearchAvailableRooms:output_type -> room.ListRoomsResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_room_room_proto_init() }
func file_proto_room_room_proto_init() {
	if File_proto_room_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_room_proto_rawDesc), len(file_proto_room_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_room_proto_goTypes,
		DependencyIndexes: file_proto_room_room_proto_depIdxs,
		MessageInfos:      file_proto_room_room_proto_msgTypes,
	}.Build()
	File_proto_room_room_proto = out.File
	file_proto_room_room_proto_goTypes = nil
	file_proto_room_room_proto_depIdxs = nil
}
